import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WalletKit from "./components/WalletKit";
import { ConnectButton } from "@rainbow-me/rainbowkit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EVM Contract Debug",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletKit>
          <header className="flex flex-row justify-between items-center px-6 py-3 border-b border-gray-300 bg-black">
            <h1 className="text-white font-bold">EVM Contract Debug</h1>
            <ConnectButton />
          </header>
          {children}
        </WalletKit>
      </body>
    </html>
  );
}
